# The use of the "$COMMIT_SHA" substitution variable is populated by Cloud Build when triggered from a Git repository.
# $PROJECT_ID: ID of your Cloud project
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
steps:
# 1) Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA', '.']
# 2) Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']
# 3) Deploy container image to Cloud Run
    #  Service name must use only lowercase alphanumeric characters and dashes (-).Cannot begin or end with a dash, and cannot be longer than 63 characters.
    # get --region from https://cloud.google.com/run/docs/locations
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['run.sh', '||', 'exit', '0']
  env:
  - 'COMMITsha=$COMMIT_SHA'
  - 'PROJECTid=$PROJECT_ID'
  - 'SERVICE_NAME=${_SERVICE_NAME}'
  - 'region=us-central1'
  - 'name_secret=SERVICEACCOUNT_cloud_run'
  - 'img=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
# Substitutions must begin with an underscore (_) 
substitutions:
    _SERVICE_NAME: 'cloudbuild-dokerfile-example-run'
images:
- 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
